create table songs (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  tempo real default 127.0
);

create table patterns (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) not null,
  song_id bigint references songs (id) not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  pattern_index int
);

create table steps (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) not null,
  pattern_id bigint references patterns (id) not null,
  track_index smallint not null,
  step_index smallint not null,
  enabled boolean default false,
  accented boolean default false,
  coarse_pitch smallint default 0,
  detune smallint default 0,
  parameters jsonb
);

create table tracks (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) not null,
  song_id bigint references songs (id) not null,
  track_index int,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  muted boolean not null,
  soloed boolean not null,
  gain float4 not null,
  parameters jsonb
);